export interface SourceLocation {
  start: { line: number; column: number };
  end: { line: number; column: number };
}

export interface AstNode {
  type: string;
  loc?: SourceLocation;
  [key: string]: unknown;
}

export interface ReportDescriptor {
  node: AstNode;
  message: string;
}

export interface RuleContext {
  report: (descriptor: ReportDescriptor) => void;
  getFilename?: () => string | undefined;
  settings?: Record<string, unknown>;
  /** Capability tokens detected for the project (e.g. 'auto-imports:vue'). */
  capabilities?: Set<string>;
}

export type RuleVisitor = (node: AstNode) => void;

export interface Rule {
  create: (context: RuleContext) => Record<string, RuleVisitor>;
  /** Optional auto-fix for findings generated by this rule. Returns the fixed text or null if not fixable. */
  fix?: (node: AstNode) => string | null;
}

export interface Plugin {
  meta: { name: string };
  rules: Record<string, Rule>;
}
